version: '3'

services:
  backend:
    container_name: $CONTAINER_NAME
    image: $IMAGE_BUILD_LOCAL
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./app:/app

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: biblioteca